repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4  # Совпадает с установленной версией ruff
    hooks:
      - id: ruff
        args: [--fix]  # Автоматически исправляет ошибки
      - id: ruff-format  # Применяет форматирование кода
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3  # Updated to a valid version
    hooks:
      - id: isort  # Сортировка импортов
