[tool.ruff]
target-version = "py312"
line-length = 120
indent-width = 4
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".ruff_cache",
    "backup_before_refactor"
]

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
fixable = ["E", "F", "I", "W"]

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
